<a href="https://colab.research.google.com/github/ishitathakwani7265/ML/blob/main/practical5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [631]:
import pandas as pd
import numpy as np

In [632]:
df = pd.read_csv('/content/01 covid_toy (1).csv')

df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [633]:
print(df.cough.value_counts())

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [634]:
print()

print(df.city.value_counts())

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [635]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [636]:
X = df.iloc[:, 0:5]
y = df.drop(X, axis='columns')

In [637]:
print(X.head())
print()
print()
print()

print(y.head())

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai



  has_covid
0        No
1       Yes
2        No
3        No
4        No

In [638]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2
)

print(x_train.head())

print()
print()

print(y_train.head())

    age  gender  fever   cough       city
18   64  Female   98.0    Mild  Bangalore
26   19  Female  100.0    Mild    Kolkata
38   49  Female  101.0    Mild      Delhi
57   49  Female   99.0  Strong  Bangalore
50   19    Male  101.0    Mild      Delhi


   has_covid
18       Yes
26       Yes
38       Yes
57        No
50       Yes

In [639]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [640]:
si = SimpleImputer()
le = LabelEncoder()

In [641]:
y_train['has_covid'] = le.fit_transform(y_train['has_covid'])
y_test['has_covid'] = le.transform(y_test['has_covid'])

In [642]:
x_train['fever'] = si.fit_transform(x_train[['fever']])

In [643]:
x_test.fever = si.transform(x_test[['fever']])

In [644]:
from sklearn.preprocessing import OrdinalEncoder

In [645]:
oe = OrdinalEncoder()

x_train['cough'] = oe.fit_transform(x_train[['cough']])
x_test['cough'] = oe.transform(x_test[['cough']])

In [646]:
from sklearn.preprocessing import OneHotEncoder

In [647]:
ohe = OneHotEncoder(drop='first', sparse_output=False)

In [648]:
x_train_gender_city = ohe.fit_transform(x_train[['gender', 'city']])
x_test_gender_city = ohe.transform(x_test[['gender', 'city']])

print(x_train_gender_city.shape)
print(x_test_gender_city.shape)

(80, 4)
(20, 4)

In [649]:
x_train

    age  gender  fever  cough       city
18   64  Female   98.0    0.0  Bangalore
26   19  Female  100.0    0.0    Kolkata
38   49  Female  101.0    0.0      Delhi
57   49  Female   99.0    1.0  Bangalore
50   19    Male  101.0    0.0      Delhi
..  ...     ...    ...    ...        ...
20   12    Male   98.0    1.0  Bangalore
49   44    Male  104.0    0.0     Mumbai
69   73  Female  103.0    0.0      Delhi
66   51    Male  104.0    0.0    Kolkata
72   83  Female  101.0    0.0    Kolkata

[80 rows x 5 columns]

In [650]:
from sklearn.compose import ColumnTransformer

In [651]:
transformer = [
    ('trans1', SimpleImputer(), ['fever']),
    ('trans2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('trans3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])
]

ct = ColumnTransformer(transformers=transformer, remainder='passthrough').set_output(transform='pandas')

In [653]:
x_train_trans = ct.fit_transform(x_train)

ValueError: could not convert string to float: 'Mild'

In [ ]:
x_train_trans.sample(5)
print()
print()

print(x_test_trans.shape)